---@module 'hl'

require("conf.host-specific")
require("conf.monitors")
require("conf.init")
require("conf.misc")
require("conf.env")
require("conf.inputs")
require("conf.colors")
require("conf.general")
require("conf.visuals")
require("conf.layout")
require("conf.windowrules")
require("conf.layerrules")
require("conf.bindings")
