-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

--

require("conf.host-specific")
require("conf.monitors")
require("conf.init")
require("conf.misc")
require("conf.env")
require("conf.inputs")
require("conf.colors")
require("conf.general")
require("conf.visuals")
require("conf.layout")
require("conf.windowrules")
require("conf.layerrules")
require("conf.bindings")

