-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

local mainMod = "SUPER"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("alacritty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "Escape", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

hl.bind(mainMod .. " + " .. "space", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- bind = $mainMod CTRL, Return, exec, wofi --show drun # with waybar

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Return", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher toggle"))

-- with noctalia

--bind = $mainMod CTRL, Return, exec, dms ipc call spotlight toggle # with dms

hl.bind(mainMod .. " + " .. "M", hl.dsp.layout("swapwithmaster master"))

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "W", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper.sh select"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("pkill waybar ; waybar"))

-- Screenshot

hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m active -m output"))

hl.bind("ALT" .. " + " .. "Print", hl.dsp.exec_cmd("hyprshot -m active -m window"))

hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("hyprshot -m region"))

-- Clipboard manager

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("cliphist list| wofi --dmenu| cliphist decode| wl-copy"))

-- Multimedia

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl --player=spotify play-pause"), { locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl --player=spotify next"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl --player=spotify previous"), { locked = true })

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
--hl.bind(mainMod .. " + " .. "left", function()
--	return hl.dispatch(hl.dsp.focus({ direction = "left" }))
--end)

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. "ampersand", hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "eacute", hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "quotedbl", hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "apostrophe", hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "parenleft", hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "section", hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "egrave", hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "exclam", hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "ccedilla", hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "agrave", hl.dsp.focus({ workspace = 10 }))

-- Switch monitor with mainMod + F[1-2]

hl.bind(mainMod .. " + " .. "F1", hl.dsp.focus({ monitor = 0 }))

hl.bind(mainMod .. " + " .. "F2", hl.dsp.focus({ monitor = 1 }))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mainMod + SHIFT + F1", hl.dsp.movecurrentworkspacetomonitor(0))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F1", hl.dsp.workspace.move({ monitor = 0 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F1", hl.dsp.focus({ monitor = 0 }))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mainMod + SHIFT + F2", hl.dsp.movecurrentworkspacetomonitor(1))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F2", hl.dsp.workspace.move({ monitor = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F2", hl.dsp.focus({ monitor = 1 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "ampersand", hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "eacute", hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "quotedbl", hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "apostrophe", hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "parenleft", hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "section", hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "egrave", hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "exclam", hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "ccedilla", hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "agrave", hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })
