-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

global background = "rgb(0c040c)"

global foreground = "rgb(b1c0f2)"

global color0 = "rgb(ffff00)"

global color1 = "rgb(cccc00)"

global color2 = "rgb(4d4d00)"

global color3 = "rgb(8F3357)"

global color4 = "rgb(AA4464)"

global color5 = "rgb(59479F)"

global color6 = "rgb(C15C9E)"

global color7 = "rgb(b1c0f2)"

global color8 = "rgb(7b86a9)"

global color9 = "rgb(59205C)"

global color10 = "rgb(614F69)"

global color11 = "rgb(8F3357)"

global color12 = "rgb(AA4464)"

global color13 = "rgb(59479F)"

global color14 = "rgb(C15C9E)"

global color15 = "rgb(b1c0f2)"
