-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local background = "rgb(0c040c)"

local foreground = "rgb(b1c0f2)"

local color0 = "rgb(ffff00)"

local color1 = "rgb(cccc00)"

local color2 = "rgb(4d4d00)"

local color3 = "rgb(8F3357)"

local color4 = "rgb(AA4464)"

local color5 = "rgb(59479F)"

local color6 = "rgb(C15C9E)"

local color7 = "rgb(b1c0f2)"

local color8 = "rgb(7b86a9)"

local color9 = "rgb(59205C)"

local color10 = "rgb(614F69)"

local color11 = "rgb(8F3357)"

local color12 = "rgb(AA4464)"

local color13 = "rgb(59479F)"

local color14 = "rgb(C15C9E)"

local color15 = "rgb(b1c0f2)"
