-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Some default env vars.

hl.env("XCURSOR_SIZE", 24)

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_MENU_PREFIX", "arch-")

hl.env("GDK_BACKEND", "wayland,x11")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

hl.env("QT_QPA_PLATFORMTHEME_QT6", "qt6ct")

hl.env("SDL_VIDEODRIVER", "wayland")

hl.env("CLUTTER_BACKEND", "wayland")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("GTK_THEME", "Nordic")

hl.env("MOZ_ENABLE_WAYLAND", 1)

hl.env("HYPRLAND_NO_SD_NOTIFY", 1)

hl.env("OZONE_PLATFORM", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.env("HYPRSHOT_DIR", "/home/monkey/Pictures/Screenshots")
