-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'



-- render {

--     explicit_sync = 1

--     explicit_sync_kms = 0

-- }

-- opengl {

--     nvidia_anti_flicker = true

--     force_introspection = 2

-- }

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("/usr/bin/hp-systray")
end)
