-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Execute your favorite apps at launch

-- exec-once = waybar & hyprpaper & firefox






--exec-once = waybar


--exec-once = dms run





-- Stores only text data


-- Stores only image data


-- exec-once = hyprpaper




--exec-once = systemctl --user start org.kde.xwaylandvideobridge.service

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("~/.config/hypr/scripts/xdg.sh")
    hl.exec_cmd("~/.config/hypr/scripts/gtk.sh")
    hl.exec_cmd("/usr/lib/pam_kwallet_init")
    hl.exec_cmd("qs -c noctalia-shell")
    hl.exec_cmd("systemctl --user restart pipewire")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
    hl.exec_cmd("mako --default-timeout 3000")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("sleep 2 ; blueman-applet")
end)
