-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    input = {
        kb_layout = "be",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        numlock_by_default = true,
        follow_mouse = 0,
        float_switch_override_focus = 0,
        accel_profile = "adaptive",
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
    },
})

hl.config({
    cursor = {
        inactive_timeout = 3,
        enable_hyprcursor = false,
        no_hardware_cursors = true,
    },
})

-- gestures {

--     # See https://wiki.hyprland.org/Configuring/Variables/ for more

--     workspace_swipe = off

-- }

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

hl.device({
    name = "corsair-corsair-harpoon-rgb-pro-gaming-mouse",
    sensitivity = -0.7,
})

hl.device({
    name = "gxt-101-gaming-mouse",
    sensitivity = 0.1,
})
