-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 15,
        blur = {
            enabled = false,
            size = 3,
        },
        active_opacity = 0.95,
        inactive_opacity = 0.8,
        shadow = {
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
    },
})

hl.config({
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- render {

--     explicit_sync = 0

-- }
