-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Example windowrule

-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

hl.window_rule({
    name  = "wofi",
    match = {
        class = "(wofi)",
    },
    rounding = 3,
})

hl.window_rule({
    name  = "fullscreen",
    match = {
        initial_class = "(firefox)|(Brave-browser)|(vlc)",
    },
    idle_inhibit = "fullscreen",
})

hl.window_rule({
    name  = "fiorefox",
    match = {
        initial_class = "(firefox)",
    },
    tile = true,
})

hl.window_rule({
    name  = "spotify",
    match = {
        class = "(Spotify)|(spotify)",
    },
    workspace = 9,
})

hl.window_rule({
    name  = "mattermost",
    match = {
        class = "(Mattermost)|(com.mattermost.Desktop)",
    },
    workspace = 8,
})

hl.window_rule({
    name  = "slack",
    match = {
        class = "(com.slack.Slack)",
    },
    workspace = 8,
})

hl.window_rule({
    name  = "neochat",
    match = {
        class = "(org.kde.neochat)",
    },
    workspace = 8,
})

hl.window_rule({
    name  = "zoom",
    match = {
        class = "(zoom)",
    },
    workspace = 8,
})

hl.window_rule({
    name  = "discord",
    match = {
        class = "(discord)",
    },
    workspace = 8,
})

hl.window_rule({
    name  = "vscode",
    match = {
        class = "(Code)|(code-oss)|(code)",
    },
    workspace = 4,
})

hl.window_rule({
    name  = "kdevelop",
    match = {
        class = "(kdevelop)",
    },
    workspace = 4,
})

hl.window_rule({
    name  = "Zed",
    match = {
        class = "(dev.zed.Zed)",
    },
    workspace = 4,
})

hl.window_rule({
    name  = "thunderbird",
    match = {
        initial_class = "(thunderbird)|(org.mozilla.Thunderbird)",
    },
    workspace = 7,
    tile = true,
})

hl.window_rule({
    name  = "protonmail",
    match = {
        class = "(me.proton.Mail)",
    },
    workspace = 7,
    tile = true,
})

hl.window_rule({
    name  = "onlyoffice",
    match = {
        class = "(ONLYOFFICE Desktop Editors)",
    },
    tile = true,
})

hl.window_rule({
    name  = "xwaylandvideobridge",
    match = {
        class = "xwaylandvideobridge",
    },
    opacity = 0.0,
    no_initial_focus = true,
    no_focus = true,
    no_blur = true,
    no_anim = true,
    max_size = { 1, 1 },
})
