import = [
    "~/.cache/wal/colors-alacritty.toml"
]
[font]
size = 9.0

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 10000
multiplier = 1

[shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
dynamic_title = true
dynamic_padding = false
padding = { x = 8, y = 5 }
