-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Auto-generated by DMS - do not edit manually

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 4,
        border_size = 2,
    },
})

hl.config({
    decoration = {
        rounding = 12,
    },
})
