-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Auto-generated by DMS - do not edit manually

hl.monitor({
    output   = "DP-2",
    mode     = "3840x2160@60.000",
    position = "3840x0",
    scale    = 1,
    vrr = 0,
})

hl.monitor({
    output   = "DP-1",
    mode     = "3840x2160@60.000",
    position = "0x0",
    scale    = 1,
    vrr = 0,
})
